"""Implementation of statechart motor_control.
Generated by YAKINDU Statechart Tools code generator.
"""

import queue
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../src')))
from yakindu.rx import Observable

class MotorControl:
	"""Implementation of the state machine MotorControl.
	"""

	class State:
		""" State Enum
		"""
		(
			motor_control_motor_control,
			motor_control_motor_control_r1breaking,
			motor_control_motor_control_r1accelerating,
			motor_control_motor_control_r1cruising,
			motor_control_motor_control_r2default,
			null_state
		) = range(6)
	
	
	def __init__(self):
		""" Declares all necessary variables including list of states, histories etc. 
		"""
		
		self.target_speed = None
		self.set_target_speed = None
		self.set_target_speed_value = None
		self.set_actual_speed = None
		self.set_actual_speed_value = None
		self.set_acceleration = None
		self.set_acceleration_value = None
		self.set_acceleration_observable = Observable()
		
		self.in_event_queue = queue.Queue()
		# enumeration of all states:
		self.__State = MotorControl.State
		self.__state_conf_vector_changed = None
		self.__state_vector = [None] * 2
		for __state_index in range(2):
			self.__state_vector[__state_index] = self.State.null_state
		
		# initializations:
		self.target_speed = 0
		self.__is_executing = False
		self.__state_conf_vector_position = None
	
	def is_active(self):
		"""Checks if the state machine is active.
		"""
		return self.__state_vector[0] is not self.__State.null_state or self.__state_vector[1] is not self.__State.null_state
	
	def is_final(self):
		"""Checks if the statemachine is final.
		Always returns 'false' since this state machine can never become final.
		"""
		return False
			
	def is_state_active(self, state):
		"""Checks if the state is currently active.
		"""
		s = state
		if s == self.__State.motor_control_motor_control:
			return (self.__state_vector[0] >= self.__State.motor_control_motor_control)\
				and (self.__state_vector[0] <= self.__State.motor_control_motor_control_r2default)
		if s == self.__State.motor_control_motor_control_r1breaking:
			return self.__state_vector[0] == self.__State.motor_control_motor_control_r1breaking
		if s == self.__State.motor_control_motor_control_r1accelerating:
			return self.__state_vector[0] == self.__State.motor_control_motor_control_r1accelerating
		if s == self.__State.motor_control_motor_control_r1cruising:
			return self.__state_vector[0] == self.__State.motor_control_motor_control_r1cruising
		if s == self.__State.motor_control_motor_control_r2default:
			return self.__state_vector[1] == self.__State.motor_control_motor_control_r2default
		return False
		
	def __execute_queued_event(self, func):
		func()
	
	def __get_next_event(self):
		if not self.in_event_queue.empty():
			return self.in_event_queue.get()
		return None
	
	def raise_set_target_speed(self, value):
		"""Raise method for event set_target_speed.
		"""
		self.in_event_queue.put(lambda: self.__raise_set_target_speed_call(value))
		self.run_cycle()
	
	def __raise_set_target_speed_call(self, value):
		"""Raise callback for event set_target_speed.
		"""
		self.set_target_speed = True
		self.set_target_speed_value = value
	
	def raise_set_actual_speed(self, value):
		"""Raise method for event set_actual_speed.
		"""
		self.in_event_queue.put(lambda: self.__raise_set_actual_speed_call(value))
		self.run_cycle()
	
	def __raise_set_actual_speed_call(self, value):
		"""Raise callback for event set_actual_speed.
		"""
		self.set_actual_speed = True
		self.set_actual_speed_value = value
	
	def __entry_action_motor_control_motor_control_r1_breaking(self):
		"""Entry action for state 'breaking'..
		"""
		self.set_acceleration_observable.next(-10)
		
	def __entry_action_motor_control_motor_control_r1_accelerating(self):
		"""Entry action for state 'accelerating'..
		"""
		self.set_acceleration_observable.next(10)
		
	def __entry_action_motor_control_motor_control_r1_cruising(self):
		"""Entry action for state 'cruising'..
		"""
		self.set_acceleration_observable.next(0)
		
	def __enter_sequence_motor_control_motor_control_default(self):
		"""'default' enter sequence for state MotorControl.
		"""
		self.__enter_sequence_motor_control_motor_control_r1_default()
		self.__enter_sequence_motor_control_motor_control_r2_default()
		
	def __enter_sequence_motor_control_motor_control_r1_breaking_default(self):
		"""'default' enter sequence for state breaking.
		"""
		self.__entry_action_motor_control_motor_control_r1_breaking()
		self.__state_vector[0] = self.State.motor_control_motor_control_r1breaking
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_motor_control_motor_control_r1_accelerating_default(self):
		"""'default' enter sequence for state accelerating.
		"""
		self.__entry_action_motor_control_motor_control_r1_accelerating()
		self.__state_vector[0] = self.State.motor_control_motor_control_r1accelerating
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_motor_control_motor_control_r1_cruising_default(self):
		"""'default' enter sequence for state cruising.
		"""
		self.__entry_action_motor_control_motor_control_r1_cruising()
		self.__state_vector[0] = self.State.motor_control_motor_control_r1cruising
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_motor_control_motor_control_r2_default_default(self):
		"""'default' enter sequence for state Default.
		"""
		self.__state_vector[1] = self.State.motor_control_motor_control_r2default
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_motor_control_default(self):
		"""'default' enter sequence for region MotorControl.
		"""
		self.__react_motor_control__entry_default()
		
	def __enter_sequence_motor_control_motor_control_r1_default(self):
		"""'default' enter sequence for region r1.
		"""
		self.__react_motor_control_motor_control_r1__entry_default()
		
	def __enter_sequence_motor_control_motor_control_r2_default(self):
		"""'default' enter sequence for region r2.
		"""
		self.__react_motor_control_motor_control_r2__entry_default()
		
	def __exit_sequence_motor_control_motor_control_r1_breaking(self):
		"""Default exit sequence for state breaking.
		"""
		self.__state_vector[0] = self.State.null_state
		self.__state_conf_vector_position = 0
		
	def __exit_sequence_motor_control_motor_control_r1_accelerating(self):
		"""Default exit sequence for state accelerating.
		"""
		self.__state_vector[0] = self.State.null_state
		self.__state_conf_vector_position = 0
		
	def __exit_sequence_motor_control_motor_control_r1_cruising(self):
		"""Default exit sequence for state cruising.
		"""
		self.__state_vector[0] = self.State.null_state
		self.__state_conf_vector_position = 0
		
	def __exit_sequence_motor_control_motor_control_r2_default(self):
		"""Default exit sequence for state Default.
		"""
		self.__state_vector[1] = self.State.null_state
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_motor_control(self):
		"""Default exit sequence for region MotorControl.
		"""
		state = self.__state_vector[0]
		if state == self.State.motor_control_motor_control_r1breaking:
			self.__exit_sequence_motor_control_motor_control_r1_breaking()
		elif state == self.State.motor_control_motor_control_r1accelerating:
			self.__exit_sequence_motor_control_motor_control_r1_accelerating()
		elif state == self.State.motor_control_motor_control_r1cruising:
			self.__exit_sequence_motor_control_motor_control_r1_cruising()
		state = self.__state_vector[1]
		if state == self.State.motor_control_motor_control_r2default:
			self.__exit_sequence_motor_control_motor_control_r2_default()
		
	def __react_motor_control__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		self.__enter_sequence_motor_control_motor_control_default()
		
	def __react_motor_control_motor_control_r1__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		self.__enter_sequence_motor_control_motor_control_r1_cruising_default()
		
	def __react_motor_control_motor_control_r2__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		self.__enter_sequence_motor_control_motor_control_r2_default_default()
		
	def __react(self, transitioned_before):
		"""Implementation of __react function.
		"""
		return transitioned_before
	
	
	def __motor_control_motor_control_react(self, transitioned_before):
		"""Implementation of __motor_control_motor_control_react function.
		"""
		transitioned_after = transitioned_before
		#If no transition was taken then execute local reactions
		if transitioned_after == transitioned_before:
			transitioned_after = self.__react(transitioned_before)
		return transitioned_after
	
	
	def __motor_control_motor_control_r1_breaking_react(self, transitioned_before):
		"""Implementation of __motor_control_motor_control_r1_breaking_react function.
		"""
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if (self.set_actual_speed) and (self.set_actual_speed_value <= self.target_speed):
				self.__exit_sequence_motor_control_motor_control_r1_breaking()
				self.__enter_sequence_motor_control_motor_control_r1_cruising_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __motor_control_motor_control_r1_accelerating_react(self, transitioned_before):
		"""Implementation of __motor_control_motor_control_r1_accelerating_react function.
		"""
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if (self.set_actual_speed) and (self.set_actual_speed_value >= self.target_speed):
				self.__exit_sequence_motor_control_motor_control_r1_accelerating()
				self.__enter_sequence_motor_control_motor_control_r1_cruising_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __motor_control_motor_control_r1_cruising_react(self, transitioned_before):
		"""Implementation of __motor_control_motor_control_r1_cruising_react function.
		"""
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if (self.set_actual_speed) and (self.set_actual_speed_value <= (self.target_speed - 0.5)):
				self.__exit_sequence_motor_control_motor_control_r1_cruising()
				self.__enter_sequence_motor_control_motor_control_r1_accelerating_default()
				transitioned_after = 0
			elif (self.set_actual_speed) and (self.set_actual_speed_value >= (self.target_speed + 0.5)):
				self.__exit_sequence_motor_control_motor_control_r1_cruising()
				self.__enter_sequence_motor_control_motor_control_r1_breaking_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __motor_control_motor_control_r2_default_react(self, transitioned_before):
		"""Implementation of __motor_control_motor_control_r2_default_react function.
		"""
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.set_target_speed:
				self.__exit_sequence_motor_control_motor_control_r2_default()
				self.target_speed = self.set_target_speed_value
				self.__enter_sequence_motor_control_motor_control_r2_default_default()
				self.__motor_control_motor_control_react(0)
				transitioned_after = 1
		#If no transition was taken then execute local reactions
		if transitioned_after == transitioned_before:
			transitioned_after = self.__motor_control_motor_control_react(transitioned_before)
		return transitioned_after
	
	
	def __clear_in_events(self):
		"""Implementation of __clear_in_events function.
		"""
		self.set_target_speed = False
		self.set_actual_speed = False
	
	
	def __micro_step(self):
		"""Implementation of __micro_step function.
		"""
		transitioned = -1
		self.__state_conf_vector_position = 0
		state = self.__state_vector[0]
		if state == self.State.motor_control_motor_control_r1breaking:
			transitioned = self.__motor_control_motor_control_r1_breaking_react(transitioned)
		elif state == self.State.motor_control_motor_control_r1accelerating:
			transitioned = self.__motor_control_motor_control_r1_accelerating_react(transitioned)
		elif state == self.State.motor_control_motor_control_r1cruising:
			transitioned = self.__motor_control_motor_control_r1_cruising_react(transitioned)
		if self.__state_conf_vector_position < 1:
			state = self.__state_vector[1]
			if state == self.State.motor_control_motor_control_r2default:
				transitioned = self.__motor_control_motor_control_r2_default_react(transitioned)
	
	
	def run_cycle(self):
		"""Implementation of run_cycle function.
		"""
		if self.__is_executing:
			return
		self.__is_executing = True
		next_event = self.__get_next_event()
		if next_event is not None:
			self.__execute_queued_event(next_event)
		condition_0 = True
		while condition_0:
			self.__micro_step()
			self.__clear_in_events()
			next_event = self.__get_next_event()
			if next_event is not None:
				self.__execute_queued_event(next_event)
			condition_0 = self.set_target_speed or self.set_actual_speed
		self.__is_executing = False
	
	
	def enter(self):
		"""Implementation of enter function.
		"""
		if self.__is_executing:
			return
		self.__is_executing = True
		self.__enter_sequence_motor_control_default()
		self.__is_executing = False
	
	
	def exit(self):
		"""Implementation of exit function.
		"""
		if self.__is_executing:
			return
		self.__is_executing = True
		self.__exit_sequence_motor_control()
		self.__is_executing = False
	
	
	
